### ISSUE TITLE
请问怎么访问页面地址

### ISSUE THREAD

**Issue by dailingx** [Li-Zhenghao-Harbin/ecommerce-platform#1]
项目通过springboot启动后，怎么访问网站的入口网址呢

**Comment by dailingx** [comment]
请问有项目的sql文件吗

**Comment by Li-Zhenghao-Harbin** [comment]
springboot启动后，可以通过web文件夹下的login.html进入用户登录界面，推荐使用firefox浏览器。
sql文件已经上传到github了，可以通过navicat运行ecommerce.sql文件从而导入表。

**Comment by dailingx** [comment]
多谢
