### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by koppetl** [Li-Zhenghao-Harbin/ecommerce-platform#2]
你好，我想问一下为什么这个项目配置好之后可以启动，但是打开页面就会显示Whitelabel Error Page

**Comment by Li-Zhenghao-Harbin** [comment]
是在登录界面(login.html)报错的吗？具体的url和错误信息是怎样的？

**Comment by koppetl** [comment]
<img width="522" alt="image" src="https://github.com/Li-Zhenghao-Harbin/ecommerce-platform/assets/137592732/a1639d96-182f-4744-b032-1b421bb33364">

**Comment by Li-Zhenghao-Harbin** [comment]
运行springboot之后，直接打开web文件夹下的login.html就可以了，不用localhost，推荐使用firefox浏览器

**Comment by koppetl** [comment]
运行起了，谢谢大佬。还有一个小问题：添加商品的图片链接是电脑上的地址还是项目里的地址？

**Comment by Li-Zhenghao-Harbin** [comment]
这里用的是网络上的图片的地址，可以通过浏览器打开网站找到合适的图片后右键“复制图片地址”即可

如果想改成项目内的图片，可以修改platform.html文件中的<img>标签，把src改成对应的路径

**Comment by koppetl** [comment]
谢谢大佬
